image: node:16.15.1

stages:
    - install
    - build
    - test
    - chromatic
    - publish

###############################################################################
#     install                                                         #
###############################################################################

install:
    stage: install
    only:
        - merge_requests
        - develop
        - main
    before_script:
        - echo -e 'Warming up the cache'
    script:
        - npm i
    cache:
        key: $CI_PROJECT_ID
        policy: pull-push
        paths:
            - node_modules

    ###############################################################################
#     build                                                         #
###############################################################################

build:
    stage: build
    needs:
        - install
    cache:
        key: $CI_PROJECT_ID
        policy: pull
        paths:
            - node_modules
    only:
        - merge_requests
        - develop
        - main
    script:
        - npm run build-lib
    dependencies:
        - install

###############################################################################
#     test                                                         #
###############################################################################

test:
    stage: test
    needs:
        - install
        - build
    cache:
        key: $CI_PROJECT_ID
        policy: pull
        paths:
            - node_modules
    script:
        - npm run test
    only:
        - merge_requests
        - develop
        - main
    dependencies:
        - install
        - build

        ###############################################################################
#     chromatic                                                         #
###############################################################################

chromatic_publish:
    stage: chromatic
    needs:
        - install
        - build
        - test
    cache:
        key: $CI_PROJECT_ID
        policy: pull
        paths:
            - node_modules
    only:
        - develop
        - main
    script:
        - npm run build-storybook
        - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-once-uploaded --exit-zero-on-changes
    dependencies:
        - install
        - build
        - test

        ###############################################################################
#     publish                                                         #
###############################################################################

publish:
    stage: publish
    only:
        - main
    before_script:
        - npm i
        - npm run build-lib
    script:
        - echo '//registry.npmjs.org/:_authToken=$NPM_TOKEN'>.npmrc
        - npm publish
    dependencies:
        - install
        - build
        - test
        - chromatic_publish
