image: node:16.15.1

stages:
    # - install
    - build
    - test
    - chromatic

###############################################################################
#     install                                                         #
###############################################################################

# install:
#     stage: install
#     only:
#         - merge_requests
#         - main
#     before_script:
#         - echo -e 'Warming up the cache'
#     script:
#         - npm i
#     cache:
#         key: $CI_PROJECT_ID
#         policy: pull-push
#         paths:
#             - node_modules

###############################################################################
#     build                                                         #
###############################################################################

build:
    stage: build
    # needs:
    #     - install
    # cache:
    #     key: $CI_PROJECT_ID
    #     policy: pull
    #     paths:
    #         - node_modules
    only:
        - merge_requests
        - main
    before_script:
        - npm i
    script:
        - npm run build-lib
    dependencies:
        - install

###############################################################################
#     test                                                         #
###############################################################################

test:
    stage: test
    needs:
        # - install
        - build
    # cache:
    #     key: $CI_PROJECT_ID
    #     policy: pull
    #     paths:
    #         - node_modules
    before_script:
        - npm i
    script:
        - npm run coverage
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        when: always
        paths:
            - coverage/cobertura-coverage.xml
        expire_in: 30 days
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage/cobertura-coverage.xml
    only:
        - merge_requests
        - main
    dependencies:
        # - install
        - build

        ###############################################################################
#     chromatic                                                         #
###############################################################################

chromatic_publish:
    stage: chromatic
    needs:
        # - install
        - build
        - test
    # cache:
    #     key: $CI_PROJECT_ID
    #     policy: pull
    #     paths:
    #         - node_modules
    only:
        refs:
            - main
        changes:
            - src/components/**/*
            - src/stories/**/*
            - .storybook/**/*
    before_script:
        - npm i
    script:
        - npm run build-storybook
        - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-once-uploaded --exit-zero-on-changes
    dependencies:
        # - install
        - build
        - test
