image: node:16.15.1

stages:
    - install
    - test
    - build
    - publish

variables:
    NPM_TOKEN:
        $NPM_TOKEN

        ###############################################################################
#     install                                                         #
###############################################################################

install:
    stage: install
    only:
        - merge_requests
        - develop
        - main
    before_script:
        - echo -e 'Warming up the cache'
    script:
        - npm i
    cache:
        key: $CI_PROJECT_ID
        policy: pull-push
        paths:
            - node_modules

###############################################################################
#     test                                                         #
###############################################################################

test:
    stage: test
    needs:
        - install
    before_script:
        - npm i
    script:
        - npm run test
    only:
        - merge_requests
        - develop
        - main
    dependencies:
        - install

    ###############################################################################
#     build                                                         #
###############################################################################

build:
    stage: build
    needs:
        - install
        - test
    only:
        - merge_requests
        - develop
        - main
    before_script:
        - npm i
    script:
        - npm run build-lib
    dependencies:
        - install
        - test

        ###############################################################################
#     publish                                                         #
###############################################################################

publish:
    stage: publish
    only:
        - main
    before_script:
        - npm i
        - npm run build-lib
    script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish
    dependencies:
        - install
        - build
