image: node:16.15.1

stages:
    - build
    - test
    - chromatic
    - release

build:
    stage: build
    only:
        - merge_requests
        - main
    before_script:
        - npm i
    script:
        - npm run build-lib

###############################################################################
#     test                                                         #
###############################################################################

test:
    stage: test
    needs:
        - build
    before_script:
        - npm i
    script:
        - npm run coverage
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        when: always
        paths:
            - coverage/cobertura-coverage.xml
        expire_in: 30 days
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage/cobertura-coverage.xml
    only:
        - merge_requests
        - main
    dependencies:
        - build

###############################################################################
#     chromatic                                                         #
###############################################################################

chromatic_publish:
    stage: chromatic
    needs:
        - build
        - test
    only:
        refs:
            - main
        changes:
            - src/components/**/*
            - src/stories/**/*
            - .storybook/**/*
    before_script:
        - npm i
    script:
        - npm run build-storybook
        - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-once-uploaded --exit-zero-on-changes
    dependencies:
        - build
        - test

###############################################################################
#     Releases                                                         #
###############################################################################

semantic-release:
    stage: release
    needs:
        - build
        - test
    only:
        - main
    before_script:
        - npm i
    variables:
        GITLAB_TOKEN: $GITLAB_TOKEN
        NPM_TOKEN: $NPM_TOKEN
    script:
        - npm run generate-exports
        - npm run build-lib
        - npx semantic-release
    dependencies:
        - build
        - test
