name: 'Chromatic publish'

on:
    workflow_run:
        workflows: [Tests]
        branches: [main]
        types:
            - completed
    push:
        branches:
            - main

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: npm
            - name: Install dependencies
              run: npm i
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
