name: 'Chromatic publish'

on:
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '16'
            
      - name: Install dependencies
        run: npm i

      - name: Build storybook
        run: npm run build-storybook

      - name: Publish to Chromatic
        run: npx chromatic --project-token=$projectToken --exit-once-uploaded --exit-zero-on-changes
        env:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}