name: Format code

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['main']

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
      - run: npm install

      - name: Formatting code
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci]: format code'
          branch: ${{ github.head_ref }}
